---
- name: Add admin group
  group: name={{ ADMIN_GROUP }} state=present
- name: Add admin user
  user: name={{ ADMIN_USER }} password="{{ ADMIN_PASSWORD }}" group="{{ ADMIN_GROUP }}" groups="sudo" shell=/bin/bash
- name: Add authorized keys for admin user
  authorized_key: user={{ ADMIN_USER }}
                  key="{{ lookup('file', item) }}"
  with_items: 
  - "{{ PUBLIC_KEYS }}"
